translate:
  nl:
    nav.home: 'Home'
    nav.partners: 'Partners'
    nav.sportclub: 'Sportclub'
    nav.trainer: 'Trainer'
    nav.about: 'Over Ons'
    nav.team: 'Team Sportlery'
    nav.contact: 'Contact'

  en:
    nav.home: 'Home'
    nav.partners: 'Partners'
    nav.sportclub: 'Sportclub'
    nav.trainer: 'Trainer'
    nav.about: 'About Us'
    nav.team: 'Team Sportlery'
    nav.contact: 'Contact'
